scr_textbox_start([
	"THIS IS A TEST OF THE TEXTBOX QUEUE SYSTEM.",
	"WITH ANY LUCK, I SHOULD BE ABLE TO HAVE MULTIPLE LINES.",
	"THEN WHEN IT'S DONE, IT WILL CLOSE AUTOMATICALLY!##I THINK THAT'S PRETTY NEAT."
	]);